[package]
name = "chess-lib"
version = "0.1.0"
authors = ["Ryan Norris <rnorris@palantir.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.13"
rand = "0.8.3"
