[package]
name = "chess-cli"
version = "0.1.0"
authors = ["Ryan Norris <rnorris@palantir.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess-lib = { path = "../chess-lib" }
clap = "3.0.0-beta.2"
